### ISSUE TITLE
how do you get this app started?

### ISSUE THREAD

**Issue by kylefoley76** [KonsomeJona/OctoMouse#20]
Thanks for building this software but please try to think harder about informing people how to use it.  As as I can see all you say is: 'add this app to your system preferences'.  Well, how do you add the app? If you look at all of these photos you'll see that there is no place for me to add the app 'octomouse'.
[Archive.zip](https://github.com/KonsomeJona/OctoMouse/files/2387175/Archive.zip)

**Comment by KonsomeJona** [comment]
Because you've only downloaded the source code and not the application binary. The application won't run with the source code only. I am sorry I didn't try to think harder, I thought this was common sense on GitHub.

You either have to compile the source code by yourself using XCode or you can download the application binary on [the release page of this repository]([url]https://github.com/KonsomeJona/OctoMouse/releases(url)). Using the latter, you will be able to directly run OctoMouse on your machine.
