### ISSUE TITLE
[feature-request] Document storage

### ISSUE THREAD

**Issue by jackzampolin** [KonsomeJona/OctoMouse#3]
I see visualizations in the upcoming feature list but it is not here yet. Perhaps you can document the storage for event data and then people can help themselves! This would be great for non Objective-C programmers who want to hack and create their own visualizations.

**Comment by KonsomeJona** [comment]
Hello, 
I'm not sure to understand your request, but as suggested in this comment:
https://github.com/Takohi-Jona/OctoMouse/issues/2

Exporting the data in a CSV document would be good as any developer or non-developer could import these data into their own applications or a Excel sheet in order to create their own visualizations.

**Comment by jackzampolin** [comment]
I would love that! What I'm most interested in is historical data that I could graph. Thank you!

**Comment by KonsomeJona** [comment]
I'm gonna work on it. I can't give to you an estimate right now as I'm working on my personal project during my spare time but I will keep you in touch.

**Comment by KonsomeJona** [comment]
Pull Request for this feature:
https://github.com/KonsomeJona/OctoMouse/pull/8
